(function(z){
var TK=function(a,b,c){b="new"===(b||a.jd);return c?(a=a.d.u.v().get(z.U.rp),b?-1:-a):a.Vk+(b?-1:1)};var UK=function(a){z.Ev.call(this,a);this.Vk=0;this.jd="new"};var VK=function(a,b){a.WW=b};
var WK=function(a){return(0,z.P)('\x3cdiv class\x3d"fyre '+(a.ke?"fyre-liveblog ":"")+(a.$g?"fyre-livechat ":"")+(a.uT?"fyre-bootstrap ":"")+(a.le?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Va?"fyre-avatar-disabled":"")+'"\x3e'+(a.iv?z.mm(z.Ls(a)):"")+(0,z.P)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Va?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.$n?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var XK=function(a){return(0,z.P)('\x3ca href\x3d"'+z.Q(z.R(a.Ea))+'" title\x3d"'+z.Q(a.Z)+'" data-id\x3d"'+z.Q(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.Q(a.cT)+'"\x3e\x3cimg src\x3d"'+z.Q(z.R(a.yd))+'" alt\x3d"'+z.Q(a.Z)+'" onerror\x3d"javascript:this.src\x3d\''+z.Q(z.Gm(a.Zb))+"';\" /\x3e\x3c/a\x3e")};
var YK=function(a){return(0,z.P)(z.Wq(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.O(a.j.DN)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(a.j.Ix)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(a.j.Io)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(a.j.Jx)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var ZK=function(a){return(0,z.P)('\x3cdiv class\x3d"tooltip"\x3e'+z.O(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var $K=function(){};var aL=function(a){z.Gf.call(this,a);this.vJ=new z.Pe({url:[z.w.K.TW,"stats"].join("/"),method:"POST",with_credentials:!1});this.Es=[];this.yb=z.u.setInterval((0,z.t)(this.zy,this),5E3)};var bL=function(a){return z.Oa(a,function(a){return a.rate?Math.random()<a.rate:!0})};
var cL=function(a){var b={},c=z.Oa(a,function(a){if("counter"!==a.type)return!0;a.metric in b?b[a.metric].value+=a.value:b[a.metric]=a;return!1});z.y(b,function(a){c.push(a)});return c};var dL=function(a){this.gG=!1;this.wo=[];this.yb=null;z.Gf.call(this,a)};var eL=function(a,b){z.Ij.call(this,b,a)};var fL=function(a,b){z.LF.call(this,a,b)};
var gL=function(a,b){var c=a.d.Bb;c.oh[4]&&(z.Uy(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.vr)},a)),z.Wy(c,4,(0,z.t)(function(a){b.Za(a,"threadBreakout",this.vr)})))};var hL=function(a,b){var c=[a.gm,a.Zy];a.ug&&c.push(a.ug);a.$s&&c.push(a.$s);a.$y&&c.push(a.$y);z.x(c,function(a){z.Oo(a,"fyre-stream-sort-selected")});z.Mo(b,"fyre-stream-sort-selected")};var iL=function(a,b){z.LF.call(this,a,b)};
var jL=function(a,b){z.xx.call(this,a,b);this.Zg=!1;this.mI=!!this.G.M.jG;this.Ga=new z.Fx;this.Ga.qc(this);this.Xt="archiveShowMore"};var kL=function(a,b){z.IF.call(this,a,b)};var lL=function(a,b,c){z.Zt.call(this,a,b,c);this.tz=b||"";this.rg(ZK(this.s()))};var mL=function(a,b,c){z.Tt.call(this,a,b||3,c)};var nL=function(a,b){z.T.call(this,b);this.m=a};var oL=function(a,b){z.T.call(this,b);this.dc=a};var pL=function(a,b){oL.call(this,a,b)};
var qL=function(){var a=z.u.window,b=z.u.document;function c(){var a=A.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){A.zW||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(A,g)}function f(a){var b;if(a.KO)return a;if(A.yW&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.KO=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.oT&&a.oT("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var A={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.yW,shivMethods:!1!==g.zW,type:"default",shivDocument:f};f(b)};var rL=function(a,b){z.TF.call(this,a,b);a.M.DO||qL();var c=a.u.Mb(),d=a.u.v();this.ig=new z.JF(a,c,a.Il.Da,d.$g()||z.fg);this.D(this.ig);a.M.Va||(this.un=new pL(c),this.D(this.un));this.Cr=new z.HF;this.D(this.Cr)};var sL=function(a){var b=z.E.cb();return!a.w.ke()||b};var tL=function(a){z.cz.call(this,a);this.Lm=1};var uL=function(a){z.Os.call(this,a);z.hv(a.u);this.Qb=new rL(a);this.Jq.start();this.wl(this.Qb);z.Ss(this)};
var vL=function(a,b){this.JC=eL;this.qJ=uL;z.X.Mo(b.strings||{});z.xl.call(this,a,b)};var wL=function(a){a.kk&&(a.kk.p(),delete a.kk)};z.v(UK,z.Ev);z.e=UK.prototype;z.e.il=z.l(58);z.e.iF=z.l(60);z.e.jF=z.l(59);z.e.iF=z.K(60,function(a){this.Ja||(this.ro[a]=!1,z.Fv(this,a,function(a){a.N(a.xa.Km)}))});
z.e.jF=z.K(59,function(a,b){if(!this.Ja){var c=this.d.u.v(),d=z.Eu(a,b),f=c.get(z.U.ut);c.set(z.U.rp,d.HU);z.y(d.ab,(0,z.t)(this.d.R.N,this.d.R,"bootstrap_author_received"));d.content=z.lj(d.content,function(a,b){return!z.Ta(f,b)});z.y(d.content,function(a){z.jb(d.content,z.Hv(this,a))},this);z.jb(this.Cc,z.kj(d.content,z.Bb(a)));this.Xd(a,d.content);z.Fv(this,a,function(b){b.N(b.xa.Ak,{Id:a});b.set(b.k.df,!0)})}});
z.e.il=z.K(58,function(a,b){this.Vk=a;this.jd=b||this.jd;var c=this.Jd[a]=new z.Bv;z.Yu.C();var d=this.d.u.v(),f=(0,z.t)(this.jF,this,a),g=(0,z.t)(this.iF,this,a),h=this.d.M.Qm,d=d.get(z.U.Hc),h=z.w.Bu(d,h)+String(a)+".json";z.Zu(0,h,f,g);return c});z.oG.prototype.il=z.K(57,function(a,b){this.Jk||(this.Jk=new UK(this.G));var c=this.Jk,d=TK(c,a,b);return c.il(d,a)});z.Yu.prototype.Qh=z.K(49,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.w.K.zd,z.w.af,a.na);(new z.Pe({url:a,wa:b,sa:c})).send()});
z.Vv.prototype.Qh=z.K(48,function(a){var b={na:this.d.u.v().id},c=z.Yu.C().Qh;z.Wv(this,c,b,a);return a});z.oG.prototype.Qh=z.K(47,function(){z.aw(this);this.Di=new z.Vv(this.G,void 0);var a=new z.Bv;this.Di.Qh(a);return a});z.Yu.prototype.Mh=z.K(46,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.w.K.zd,z.w.af,a.na,a.xN);(new z.Pe({url:a,wa:b,sa:c})).send({format:"stream"})});z.Vv.prototype.Mh=z.K(45,function(a,b){var c={na:this.d.u.v().id,xN:a},d=z.Yu.C().Mh;z.Wv(this,d,c,b);return b});
z.oG.prototype.Mh=z.K(44,function(a){z.aw(this);this.Di=new z.Vv(this.G,void 0);var b=new z.Bv;this.Di.Mh(a,b);return b});z.T.prototype.vG=z.K(43,function(){return this.aa});z.Fj.prototype.$n=z.K(42,function(){return this.get(this.k.qp)});z.v($K,z.Dl);z.da($K);var xL={WX:"attachmentDelegate"};z.jb(xL,z.CG);$K.prototype.Xn=function(a){var b=$K.b.Xn.call(this,a),c=a.attachmentDelegate;c&&(b.FN=c);b.Cx=a[xL.sL]||null;return b};z.v(aL,z.Gf);aL.prototype.send=function(a){this.Es=this.Es.concat(a)};aL.prototype.zy=function(){var a=cL(this.Es),a=bL(a);a.length&&this.vJ.send(z.kd(a),{"Content-Type":"application/json"});this.Es=[]};aL.prototype.p=function(){(0,window.clearInterval)(this.yb);this.vJ=null;aL.b.p.call(this)};z.v(dL,z.Gf);dL.prototype.RT=function(a){this.yb||(this.yb=z.u.setInterval((0,z.t)(this.JP,this),5E3));this.wo=this.wo.concat(a)};
dL.prototype.JP=function(){this.wo.length&&(this.gG||(z.tc("//platform.twitter.com/impressions.js"),this.gG=!0),z.u.twttr=function(){var a=z.u.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.u.twttr.impressions.ready((0,z.t)(function(a){a.impressions.logTweets(this.wo,{partner:"livefyre"});this.wo=[]},this)))};dL.prototype.p=function(){(0,window.clearInterval)(this.yb);dL.b.p.call(this)};z.v(eL,z.Ij);eL.prototype.Ky=function(a){this.yi=new z.Uu(this);this.iu=new z.Mq(this,a);this.Jc=new z.Bi(this);this.bb=new z.qv(this,a);this.Il=new z.xv(this);this.u=new z.fv(this,a);this.Kb=new z.oG(this,a);new z.rf;this.Po=new z.lw(this,a);this.UW=new aL(this);this.pX=new dL(this);this.Bb=new z.Ky(this)};z.v(fL,z.LF);z.e=fL.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.xx=b.v().ke();a.EU=!z.E.get(z.E.k.Sd);a.Bl=b.Bl(z.E.id);a.GO=2===c.get(z.U.Si);a.FO=3===c.get(z.U.Si);a.j={KT:z.X.get(z.X.g.Lt),NT:z.X.get(z.X.g.Mt),aT:z.X.get(z.X.g.LA),Ix:z.X.get(z.X.g.Kp),Jx:z.X.get(z.X.g.Lp),Io:z.X.get(z.X.g.OB),Zo:z.X.get(z.X.g.Op),jX:z.X.get(z.X.g.fC)};return a};
z.e.J=function(a){fL.b.J.call(this,a);a=this.c;var b;b=this.s();var c=z.P,d=z.Wq(b),f;f=b.xx?(0,z.P)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.EU?b.Bl?z.O(b.j.NT):z.O(b.j.KT):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(b.j.Ix)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Io)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(b.j.Jx)+"\x3c/a\x3e"+(b.GO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Io)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.O(b.j.jX)+"\x3c/a\x3e":"")+(b.FO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Io)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.O(b.j.aT)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.hl=this.n("fyre-follow-conversation");this.$s=this.n("fyre-stream-sort-hot-threads")||
null;this.$y=this.n("fyre-stream-sort-top-comments")||null;this.ug=this.n("fyre-stream-sort-back");this.gm=this.n("fyre-stream-sort-newest");this.Zy=this.n("fyre-stream-sort-oldest");this.rI=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.Ed()};z.e.l=function(){fL.b.l.call(this);var a=this.q();z.E.on(z.E.xa.Mf,this.Rn,this);a.e(this.c,"click",this.ib);z.x([3,4,5],function(b){z.MF(this,a,b)},this);gL(this,a)};
z.e.ib=function(a){a.preventDefault();a=a.target;if(!z.So(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.ug)if(a===this.hl)this.hF();else switch(hL(this,a),this.fm(),a){case this.$s:this.UD();break;case this.$y:this.dispatchEvent({type:"sortTopComments",Ub:(0,z.t)(this.Ed,this)});break;case this.gm:this.hn("new");break;case this.Zy:this.hn("old")}};z.e.vi=function(a,b){a&&this.Ly(b);z.Nn(this.rI,"display",a?"none":"block");z.Nn(this.ug,"display",a?"block":"none")};
z.e.Ly=function(a){var b=this.gm,c=this.hn,d=z.X.get(z.X.g.vt);4===a&&(b=this.$s,c=this.UD,d=z.X.get(z.X.g.EJ));this.ug.innerHTML=d;this.q().wf(this.ug,"click",(0,z.t)(function(a){a.stopPropagation();this.vi(!1);hL(this,b);c.apply(this)},this))};z.e.On=function(a){a.stopPropagation();this.vi(!1);hL(this,this.gm);this.hn()};z.e.vr=function(a){var b=a.Ub;z.jb(a,{Ub:(0,z.t)(function(){b();this.vi(!0,4)},this)})};
z.e.hn=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Ub:(0,z.t)(this.Ed,this)})};z.e.UD=function(){this.dispatchEvent({type:"sortHotThreads",Ub:(0,z.t)(this.Ed,this)})};z.e.hF=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.Bl(z.E.get(b.W)),a.sj(!b),a=b?z.X.get(z.X.g.Lt):z.X.get(z.X.g.Mt),this.hl.innerHTML=a):z.Sh(this.d.Jc,(0,z.t)(this.hF,this))};
z.e.Rn=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.ke()||z.E.get(c.Sd);this.hl&&(b?z.S(this.hl,!1):(a=a.Bl(z.E.id)?z.X.get(z.X.g.Mt):z.X.get(z.X.g.Lt),this.hl.innerHTML=a,z.S(this.hl,!0)))};z.e.h=function(){fL.b.h.call(this);z.E.off(null,null,this)};z.v(iL,fL);iL.prototype.J=function(a){this.c=a;z.Zl(a,YK,this.s());this.gm=this.n("fyre-stream-sort-newest");this.Zy=this.n("fyre-stream-sort-oldest");this.rI=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.Ed()};iL.prototype.hn=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.WW.stream,direction:a,Ub:(0,z.t)(this.Ed,this)})};
iL.prototype.s=function(){return{j:{DN:z.X.get(z.X.g.zJ),Ix:z.X.get(z.X.g.Kp),Jx:z.X.get(z.X.g.Lp),Io:z.X.get(z.X.g.OB),Zo:z.X.get(z.X.g.Op)}}};z.v(jL,z.xx);z.e=jL.prototype;z.e.Ym=function(a){this.clear();z.S(this.c,!0);this.jd=a};z.e.clear=function(){this.gd.Ld();this.ub={};this.zj=[];for(this.ph=this.Mk=null;this.ma&&0!=this.ma.length;)this.zo(0).p()};z.e.J=function(a){jL.b.J.call(this,a);z.Zl(this.c,z.Xq,this.s());this.ck=this.n("fyre-stream-content");this.wi=this.n("fyre-stream-more");this.Ga.S(this.wi);z.S(this.wi,!1)};z.e.h=function(){this.Ga&&this.Ga.p();this.Ga=null;jL.b.h.call(this)};
z.e.l=function(){jL.b.l.call(this);this.q().e(this.Ga,"showMore",this.Iw)};z.e.Kv=function(){return this.G.M.jG};z.e.s=function(){return{Rc:z.w.K.nb,bv:!!this.Ga,j:{Ry:z.X.get(z.X.g.AJ)}}};z.e.Jw=function(){this.Ga.Vs();this.Zg=!0};z.e.ay=function(){this.dispatchEvent({type:this.Xt,direction:this.jd,target:this,xX:this.Zg&&this.mI,Ub:(0,z.t)(this.Jw,this),rj:(0,z.t)(this.GF,this)});this.Zg&&(this.mI=!1)};z.e.hy=function(a){this.Zg||jL.b.hy.call(this,a)};
z.e.Oo=function(){var a=this.G.Kb.Jk,b=this.jd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.rp),c=!b&&a.Vk>-c;b&&-1>a.Vk||c?this.Ga.show():this.Ga.qb()};z.e.start=function(){this.Zg||this.ay()};z.v(kL,z.IF);var yL=z.X.g,zL={};zL.comment=[yL.Fm,yL.Nf,yL.tm];zL.liveblog=[yL.UL,yL.gL,yL.RA];kL.prototype.EE=function(a){function b(a){return z.Ga(a,"%s")?a:"%s "+a}var c=this.m.ke()?"liveblog":"comment",c=zL[c];switch(a){case 1:c=b(z.X.get(c[1]));break;case 0:if(z.X.get(c[0])!==z.GF[c[0]]){c=z.X.get(c[0]);break}default:c=b(z.X.get(c[2]))}return z.wa(c,a)};z.v(lL,z.Zt);lL.prototype.Ro=200;lL.prototype.Sh=function(){return new mL(this.Ic)};lL.prototype.s=function(){var a={};a.message=this.tz;return a};z.v(mL,z.Tt);mL.prototype.Nc=function(a,b,c){var d=z.mo(this.element),d=new z.Ch(d.width,d.height+25);b=z.Ot(this.element,this.Fh,a,b,d,c,9);z.Tn(a.lastChild,0);b&&(d=new z.Ch(0,-5),z.Ot(this.element,2,a,1,d,c,5),z.Tn(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.v(nL,z.T);z.e=nL.prototype;z.e.r=function(){this.c=z.bm(XK,this.s())};z.e.l=function(){nL.b.l.call(this);this.Ta=new lL(this.c,this.m.get("displayName"));this.q().e(this.c,"click",this.ib)};z.e.h=function(){nL.b.h.call(this);this.Ta&&this.Ta.p()};z.e.s=function(){var a=z.Wd,b={};b.yd=this.m.get(a.wb);b.Zb=this.m.get(a.rk);b.Z=this.m.get(a.ua);b.id=this.m.id;b.cT=this.m.id.replace(/[@.]/g,"-");b.Ea=this.m.get(a.Wb);return b};
z.e.ib=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};z.v(oL,z.T);z.e=oL.prototype;z.e.VA=10;z.e.h=function(){oL.b.h.call(this);delete this.dc};z.e.Q=function(){oL.b.Q.call(this);this.dc.off(null,null,this)};z.e.SE=function(a){a=new nL(a);var b=this.Mc();if(b===this.VA){var c=this.zo(b-1);c&&(c.p(),b--)}0<b?this.ze(a,0,!0):this.D(a,!0)};z.e.gS=function(a){var b;this.Tc(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.Yh=function(){this.dc.on(this.dc.xa.tt,this.SE,this);this.dc.on(this.dc.xa.Ut,this.gS,this);var a=this.dc.rb.reverse().slice(0,this.VA);z.x(a,this.SE,this)};z.v(pL,oL);z.v(rL,z.TF);
rL.prototype.KH=function(a,b){if(!this.Ja){this.w=b;var c=b.get(z.U.yh),d=b.get(z.U.Ud);this.nt=new z.QF(c,d,a.M.Va);this.D(this.nt);this.tq=new kL(a.u.v());this.D(this.tq);this.gs=null;b.$n()&&(this.tu=new iL(a),this.D(this.tu),this.Kk=new jL(a),this.D(this.Kk),VK(this.tu,{stream:this.Kk}));this.mh=new fL(a);this.D(this.mh);this.Zr((0,z.t)(function(a){this.$b=a;this.D(this.$b);a=this.$b;this.aa&&a&&a.S(this.de,!0)},this));b.get(z.U.zm)&&!z.fg&&this.w.Qq()&&(this.w.$g()||this.w.ke()||this.lw())}};
rL.prototype.s=function(){var a=!this.d.M.jq&&!z.w.$u&&!this.d.M.QD;return{QI:z.w.K.uz,RI:(0,window.encodeURIComponent)(String(window.location.href)),Va:this.d.M.Va,$g:this.w.$g(),ke:this.w.ke(),le:z.fg,iv:a,uT:this.d.M.jq,$n:this.w.$n()}};z.Lx={SX:"fyre-archive-stream",TX:"fyre-archive-stream-header",H0:"fyre-top-content-stream",$0:"fyre-widget",zm:"fyre-featured-content-wrapper"};z.jb(z.Lx,z.EJ);z.e=rL.prototype;
z.e.r=function(){this.c=z.bm(WK,this.s());var a=this.w.get(z.U.Si);if(1!==a){var b=this.d.Bb,a=2===a?3:4,c=this.n("fyre-top-content-stream");z.Ly(b,a,c,this)}this.Cr.S(this.n(z.Lx.SK));this.Kk&&(b=this.n("fyre-archive-stream-header"),this.tu.S(b),this.Kk.S(this.n("fyre-archive-stream")));this.Gh(1);this.de=this.n(z.Lx.wh);b=sL(this);z.S(this.de,b)};
z.e.l=function(){rL.b.l.call(this);var a=this.$b;this.aa&&a&&a.S(this.de,!0);this.d.R.ap("stream_data_received",this.dR,this);this.q().e(this,"request_content_context",this.DQ).e(this,"request_content_reply",this.jS);this.Kk&&this.Kk.start()};z.e.Yh=function(){this.un&&this.un.Yh();this.ig.Yh()};z.e.dR=function(){var a=this.w,b=a.get(z.U.uk);z.th||b||(b=(0,z.t)(function(){this.gs=new z.AL(this.d,a.get(z.U.Ud));this.D(this.gs,!0)},this),z.tc(z.w.K.nb+z.w.yf.gs,null,null,b))};
z.e.lw=function(){var a=new z.zE(this.vG,this);a.lH=(0,z.t)(this.VV,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.tc(z.w.K.nb+z.w.yf.mP,null,null,b)};z.e.VV=function(){var a=this.n("fyre-featured-content-wrapper");this.vv=new z.UJ(this.d);this.D(this.vv);this.vv.S(a);this.vv.Yg()};z.e.Zr=function(a){if(!this.d.M.readOnly){var b=this.d.u.v();z.Gw(z.Dw.C(),"main",a,{G:this.d,oi:"new"},b);z.E.on(z.E.jc(z.E.k.W),this.Uc,this)}};z.e.Uc=function(){if(this.de){var a=sL(this);z.S(this.de,a)}};
z.e.Xh=function(){0<z.Do(this,this.$b)&&(this.removeChild(this.$b),this.$b.p());this.Zr((0,z.t)(function(a){this.$b=a;this.D(this.$b);a=this.$b;this.aa&&a&&a.S(this.de,!0);z.S(this.de,!0)},this))};z.e.Wg=function(a){null!=a&&(this.d.Bb.nl(1),(0,window.setTimeout)((0,z.t)(function(){this.Ja||z.UF(this,a)},this),3E3))};z.e.DQ=function(a){z.UF(this,a.Qk)};z.e.jS=function(a){z.UF(this,a.Qk,function(a){z.Cw(a.Jb)})};
z.e.h=function(){rL.b.h.call(this);z.E.off(z.E.jc(z.E.k.W),this.Uc,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.v(tL,z.cz);z.e=tL.prototype;z.e.he=function(a,b){tL.b.he.call(this,a,b);a.e(b,"repliesExpanded",this.eF);a.e(b,"sortHotThreads",this.tS);a.e(b,"sortOrderChanged",this.JF);a.e(b,"sortTopComments",this.uS);a.e(b,"archiveShowMore",this.nQ);a.e(b,"archiveSortOrderChanged",this.oQ)};
z.e.nQ=function(a){var b=a.Ub||z.n,c=(0,z.t)(this.Je,this,a.target),d=this.d.Kb;a=a.xX;d.Jk||(d.Jk=new UK(d.G));d=d.Jk;a=a?d.Vk:TK(d);var f=d.rd[a];f&&(d.Vk=a);if(f)b(),c(f);else{d=this.d.Kb.il();a=d.k.df;if(d.get(a))b();else d.on(d.jc(a),b,this);z.dz(this,d,c)}};z.e.gw=function(a,b){var c=2===b.Zc,d=1!==b.Zc;switch(b.type){case 0:var f=this.d.u.v(),f=z.xk(b,f),g=f.get(z.Kk),g=this.d.u.ab().get(g);f.set(z.yk,g);a.zw(f,c,d)}};
z.e.BF=function(a){if(1!==this.Lm){var b=this.NW.mh;b.vi(!1);hL(b,b.gm);z.jb(a,{direction:"new",Ub:z.n});this.JF(a)}};z.e.oQ=function(a){z.ez(this);a.stream.Ym(a.direction);var b=this.d.Kb.il(a.direction,!0),c=(0,z.t)(function(b){a.Ub();this.Je(a.stream,b)},this);z.dz(this,b,c,a.rj)};z.e.JF=function(a){this.d.M.yl=null;var b=z.gz(this,1);z.aw(this.d.Kb);b.Ym(a.direction);var c=z.$v(this.d.Kb,a.direction),d=(0,z.t)(function(c){a.Ub();this.Je(b,c)},this);z.dz(this,c,d,a.rj)};
z.e.uS=function(a){var b=z.gz(this,3),c=this.d.Kb.Mh("likes");z.dz(this,c,(0,z.t)(function(c){a.Ub();z.gb(c)?z.wx(b):this.Je(b,c)},this))};z.e.tS=function(a){var b=z.gz(this,4),c=this.d.Kb.Qh();z.dz(this,c,(0,z.t)(function(c){a.Ub();z.gb(c)?z.wx(b):this.Je(b,c)},this))};z.v(uL,z.Os);z.e=uL.prototype;z.e.c=null;z.e.h=function(){uL.b.h.call(this);this.bt.p();this.kD.p();this.Qb.aa&&this.Qb.p();this.Lf&&this.Lf.p();delete this.Lf};z.e.wl=function(a){uL.b.wl.call(this,a);this.bt=new tL(this.d);this.bt.handle(a);this.kD=new z.$y(this.d);this.kD.handle(a)};z.e.gz=function(){this.d.yi.stop()};z.e.VW=function(){this.d.Il.stop()};z.e.$j=function(){this.d.yi.start()};z.e.RW=function(){this.d.Il.start()};
z.e.pa=function(){this.Lf&&this.Lf.p();this.Qb.pa(this.c);if("object"===typeof window.Livefyre&&window.Livefyre.pN)z.Ts(this);else{var a=z.Qs(this);this.Qb.Wg(a)}this.d.R.N("render_complete",this.c)};z.v(vL,z.xl);vL.prototype.CC=$K.C();vL.prototype.h=function(){vL.b.h.call(this);this.stop();delete this.M;delete this.ha;wL(this);z.Cl(this);this.qj&&(this.qj.p(),delete this.qj)};vL.prototype.oz=function(){this.stop();wL(this);vL.b.oz.call(this)};z.ng.main.Ih.ia(vL);})(fyre.conv);
